# Generated by Django 2.1.3 on 2018-11-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
